repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        types_or: [javascript, jsx, ts, tsx]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0 # automatically updated by Commitizen
    hooks:
    -   id: commitizen
        stages: 
            [commit-msg]
